ppo:
  policy: "MlpPolicy"
  gamma: 0.99
  learning_rate: 0.0003
  n_steps: 2048
  batch_size: 64
  n_epochs: 10
  clip_range: 0.2
  gae_lambda: 0.95
  vf_coef: 0.5
  ent_coef: 0.01
  max_grad_norm: 0.5
  verbose: 1
training:
  total_timesteps: 100000
  log_interval: 1000
tensorboard:
  log_dir: "./tensorboard_logs"

