ppo:
  policy: "MlpPolicy"
  gamma: 0.95
  learning_rate: 0.0009
  n_steps: 20
  batch_size: 300
  n_epochs: 10
  clip_range: 0.2
  gae_lambda: 0.95
  vf_coef: 0.5
  ent_coef: 0.01
  max_grad_norm: 0.5
  verbose: 1
  policy_kwargs: 
      net_arch:
        pi: [512, 256]
        vf: [64, 128]
training:
  total_timesteps: 2000000
  log_interval: 1000
tensorboard:
  log_dir: "./tensorboard_logs"

