from __future__ import annotations

"""
Data models for IBKR trading module.

Defines dataclasses for trade signals, results, positions, and order statuses.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional


class OrderAction(Enum):
    """Order action type."""
    BUY = "BUY"
    SELL = "SELL"


class OrderType(Enum):
    """Order type."""
    MARKET = "MKT"
    LIMIT = "LMT"
    STOP = "STP"
    STOP_LIMIT = "STP LMT"


class OrderStatus(Enum):
    """Order status from IBKR."""
    PENDING_SUBMIT = "PendingSubmit"
    PENDING_CANCEL = "PendingCancel"
    PRE_SUBMITTED = "PreSubmitted"
    SUBMITTED = "Submitted"
    CANCELLED = "Cancelled"
    FILLED = "Filled"
    INACTIVE = "Inactive"
    ERROR = "Error"


class ValidationStatus(Enum):
    """Validation result status."""
    APPROVED = "approved"
    REJECTED = "rejected"
    WARNING = "warning"


@dataclass
class TradeSignal:
    """
    A trading signal generated by the strategy.

    Attributes:
        symbol: Stock ticker symbol
        action: BUY or SELL
        shares: Number of shares to trade
        signal_price: Price at signal generation
        signal_time: When signal was generated
        pred_reg_3d: 3-day regression prediction
        pred_reg_10d: 10-day regression prediction
        adx_signal: ADX signal value
        cci_signal: CCI signal value
        reason: Human-readable reason for signal
    """
    symbol: str
    action: OrderAction
    shares: int
    signal_price: float
    signal_time: datetime
    pred_reg_3d: Optional[float] = None
    pred_reg_10d: Optional[float] = None
    adx_signal: Optional[float] = None
    cci_signal: Optional[float] = None
    reason: str = ""

    def __post_init__(self):
        if self.shares <= 0:
            raise ValueError(f"Shares must be positive, got {self.shares}")
        if self.signal_price <= 0:
            raise ValueError(f"Signal price must be positive, got {self.signal_price}")


@dataclass
class ValidationResult:
    """
    Result of pre-trade validation.

    Attributes:
        status: APPROVED, REJECTED, or WARNING
        signal: Original trade signal
        messages: List of validation messages/reasons
        adjusted_shares: Shares after risk adjustment (may differ from signal)
        max_allowed_shares: Maximum shares allowed by risk rules
    """
    status: ValidationStatus
    signal: TradeSignal
    messages: list[str] = field(default_factory=list)
    adjusted_shares: Optional[int] = None
    max_allowed_shares: Optional[int] = None

    @property
    def is_approved(self) -> bool:
        return self.status == ValidationStatus.APPROVED

    @property
    def is_rejected(self) -> bool:
        return self.status == ValidationStatus.REJECTED


@dataclass
class Position:
    """
    Current position in a symbol.

    Attributes:
        symbol: Stock ticker
        shares: Number of shares held (positive=long, negative=short)
        avg_cost: Average cost basis per share
        market_value: Current market value
        unrealized_pnl: Unrealized profit/loss
        realized_pnl: Realized profit/loss
        entry_date: When position was opened
    """
    symbol: str
    shares: int
    avg_cost: float
    market_value: float = 0.0
    unrealized_pnl: float = 0.0
    realized_pnl: float = 0.0
    entry_date: Optional[datetime] = None

    @property
    def is_long(self) -> bool:
        return self.shares > 0

    @property
    def is_short(self) -> bool:
        return self.shares < 0

    @property
    def is_flat(self) -> bool:
        return self.shares == 0

    @property
    def cost_basis(self) -> float:
        return abs(self.shares) * self.avg_cost


@dataclass
class OrderResult:
    """
    Result of order submission.

    Attributes:
        order_id: IBKR order ID
        symbol: Stock ticker
        action: BUY or SELL
        shares: Number of shares
        order_type: Order type (MKT, LMT, etc.)
        status: Current order status
        filled_shares: Shares filled so far
        avg_fill_price: Average fill price
        submitted_time: When order was submitted
        filled_time: When order was completely filled
        error_message: Error message if failed
    """
    order_id: int
    symbol: str
    action: OrderAction
    shares: int
    order_type: OrderType
    status: OrderStatus
    filled_shares: int = 0
    avg_fill_price: float = 0.0
    submitted_time: Optional[datetime] = None
    filled_time: Optional[datetime] = None
    error_message: str = ""

    @property
    def is_filled(self) -> bool:
        return self.status == OrderStatus.FILLED

    @property
    def is_pending(self) -> bool:
        return self.status in (
            OrderStatus.PENDING_SUBMIT,
            OrderStatus.PRE_SUBMITTED,
            OrderStatus.SUBMITTED
        )

    @property
    def is_complete(self) -> bool:
        return self.status in (
            OrderStatus.FILLED,
            OrderStatus.CANCELLED,
            OrderStatus.ERROR,
            OrderStatus.INACTIVE
        )

    @property
    def fill_ratio(self) -> float:
        if self.shares == 0:
            return 0.0
        return self.filled_shares / self.shares


@dataclass
class TradeResult:
    """
    Complete result of a trade execution.

    Attributes:
        signal: Original trade signal
        validation: Validation result
        order: Order result from IBKR
        execution_time: Time from signal to fill
        slippage: Difference between signal price and fill price
        success: Whether trade completed successfully
    """
    signal: TradeSignal
    validation: ValidationResult
    order: Optional[OrderResult] = None
    execution_time_ms: Optional[int] = None
    slippage: float = 0.0
    success: bool = False
    error_message: str = ""

    @property
    def slippage_pct(self) -> float:
        if self.signal.signal_price == 0:
            return 0.0
        return (self.slippage / self.signal.signal_price) * 100


@dataclass
class AccountSummary:
    """
    Account summary information.

    Attributes:
        net_liquidation: Total account value
        total_cash: Cash balance
        available_funds: Cash available for trading
        buying_power: Total buying power
        gross_position_value: Total value of positions
        realized_pnl: Day's realized P&L
        unrealized_pnl: Unrealized P&L
    """
    net_liquidation: float
    total_cash: float
    available_funds: float
    buying_power: float
    gross_position_value: float
    realized_pnl: float = 0.0
    unrealized_pnl: float = 0.0

    @property
    def total_pnl(self) -> float:
        return self.realized_pnl + self.unrealized_pnl


@dataclass
class DailyStats:
    """
    Daily trading statistics for risk management.

    Attributes:
        date: Trading date
        trades_executed: Number of trades today
        realized_pnl: Realized P&L today
        max_drawdown: Maximum drawdown today
        winning_trades: Number of winning trades
        losing_trades: Number of losing trades
    """
    date: datetime
    trades_executed: int = 0
    realized_pnl: float = 0.0
    max_drawdown: float = 0.0
    winning_trades: int = 0
    losing_trades: int = 0

    @property
    def win_rate(self) -> float:
        total = self.winning_trades + self.losing_trades
        if total == 0:
            return 0.0
        return self.winning_trades / total
